name: Test

on:
  push:
    branches: ["dev_nope"]
  pull_request:
    branches: ["dev_nope"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
      - run: npm i
      - run: npm run test
